### ISSUE TITLE
Is this project in development?

### ISSUE THREAD

**Issue by lars18th** [zhyonc/trayproxy#1]
Hi,

This tool is very useful to use Windows tools that only support HTTP proxies, with SSH connections (using the HTTP->Socks functionality when you have configured the Socks server in your SSH client). However, I feel the UI is quite complex to use different Socks servers. Therefore, I ask if the project is open to improve it. The simple idea is to store different configurations and change them using a menu over the right-click.

What you think?

**Comment by zhyonc** [comment]
hi, this project is in idle.Thanks your feedback.
Store different configurations is a good idea,  but I think only one of the different sock ports is active at the same time.
Do you mean right click on the configuration name in the ui instead of input socks port? Welcome to submit pull request.

**Comment by lars18th** [comment]
Hi @zhyonc ,

Thank you for the response. My idea is to provide a more _user friendly_ interface to enable/disable the different proxies. For example, when you're using a SSH session your SOCKS proxy port could change. A fast method to select 1080, or 1081 or whatever will be useful. Don't you think?
Another suggestion is to _reset_ the values when the program exits. At time is quite confusing to reboot the computer and get that the proxy continues configured. Any idea to solve this?

Regards.

**Comment by zhyonc** [comment]
@lars18th  I see, maybe this feature is what you want：
**Add new proxy row in Setting view**
![SettingDesign](https://github.com/zhyonc/trayproxy/assets/43988989/a47e5fc1-7c75-43d7-b024-243017d9a651)
**Display proxy name in Outbound tag so that you can right-click select a different port**
![OutboundDesign](https://github.com/zhyonc/trayproxy/assets/43988989/d11d3f63-b64a-4105-a5eb-898331db0a20)
I already reset the system proxy setting when the program exits, to see TrayMenuViewModel.cs
```C#
protected override void OnDispose(bool disposing)
{
    base.OnDispose(disposing);
    NotifyDispose?.Invoke(this, EventArgs.Empty);
    privoxyRunner.Stop();
    pacServer?.Stop();
    Inetcpl.OnProxyModeChanged(0); // Equivalent to click "disable" in the proxy mode tag
}
```
But when the program reopen, it will load the last selected proxy mode from local config file.

**Comment by lars18th** [comment]
Hi @zhyonc ,

> I see, maybe this feature is what you want：

This is a perfect solution! ❤️ Where to download it?

> But when the program reopen, it will load the last selected proxy mode from local config file.

To solve this, perhaps you want to implement a new configuration bool value indicating: "auto-apply on start". So, if you enable it, then you load and apply the las selected proxy mode on init. And if you don't enable it, then the program will start in "non-proxy mode". You agree with this _simple_ suggestion?

Regards.

**Comment by lars18th** [comment]
Hi @zhyonc ,

> @lars18th Hello, please try [this](https://github.com/zhyonc/sysproxy) to get new version. Old version is no longer supported.

I'm now testing it. However, I've troubles. I'll comment on the other repository.
I suggest to "freeze" this and link on the README to the new project.
